{% set name = "hyper-connections" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyper_connections-{{ version }}.tar.gz
  sha256: d36f9ea8803e82e14f233085653660ead52117ca1787186bd0fdb1970b65ce1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.8.0
    - pytorch >=2.3

test:
  imports:
    - hyper_connections
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/hyper-connections
  summary: Attempt to make multiple residual streams from Bytedance's Hyper-Connections paper accessible to the public
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
