{% set name = "hyper-connections" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyper_connections-{{ version }}.tar.gz
  sha256: e97850a0ec6d52d649b8852a5790e5e2f1810054f5dc490dad1530ce5aac2e20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.8.0
    - pytorch >=2.3

test:
  imports:
    - hyper_connections
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/hyper-connections
  summary: Attempt to make multiple residual streams from Bytedance's Hyper-Connections paper accessible to the public
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
